#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load the shell dotfiles, and then some:
for file in ~/.{path,exports,aliases,functions,extra}; do
    [ -r "$file" ] && source "$file"
done
unset file

# load iterm2 shell integration
export iterm2_hostname=$(hostname | cut -d"." -f1)
source ~/.iterm2_shell_integration.zsh
if [[ "$iterm2_hostname" =~ ^hd1 ]]; then
    printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "\(session.hostname)" | base64)
fi

source "${ZDOTDIR:-$HOME}/.iterm2.zsh"

