#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load the shell dotfiles, and then some:
for file in ~/.{path,exports,aliases,functions,extra}; do
    [ -r "$file" ] && source "$file"
done
unset file


# load iterm2 shell integration + set up badge
source ~/.iterm2_shell_integration.zsh
function iterm2_print_user_vars() {
    local host=$(hostname | cut -d"." -f1)
    if [[ "$host" =~ ^hd ]]; then
        iterm2_set_user_var hostname "$host"
    else iterm2_set_user_var hostname ""
    fi
}
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "\(user.hostname)" | base64)

source "${ZDOTDIR:-$HOME}/.iterm2.zsh"

